### ISSUE TITLE
sqsh_inode_map_get returns 0 on error, rather than a negative number

### ISSUE THREAD

**Issue by Dr-Emann** [Gottox/libsqsh#106]
**Describe the bug**

`sqsh_inode_map_get` is documented to return:

https://github.com/Gottox/libsqsh/blob/fd6ed2d9c0f70830463826b8c178dd4578acd7ed/include/sqsh_archive.h#L87

> The inode reference on success, a negative value on error.

However, it appears that the implementation actually returns zero on errors:

https://github.com/Gottox/libsqsh/blob/fd6ed2d9c0f70830463826b8c178dd4578acd7ed/lib/archive/inode_map.c#L72-L81

**Comment by Gottox** [comment]
Negative errors make no sense for uint64. You're right. Thanks for the catch!
