### ISSUE TITLE
Error SQSH_ERROR_NOT_A_FILE is unused

### ISSUE THREAD

**Issue by Dr-Emann** [Gottox/libsqsh#108]
**Describe the bug**

Error `SQSH_ERROR_NOT_A_FILE` is never created. It seems like it might be a good error for e.g. `sqsh_easy_file_content(archive, "path/to/directory", &err)` (which seems to currently error with `SQSH_ERROR_OUT_OF_BOUNDS`)

**Comment by Gottox** [comment]
There was a check for that in `sqsh_easy_file_content`. But I removed it as I expected that it was handled by the low level `sqsh__file_iterator_init` function. Apparently it was not.
