### ISSUE TITLE
sqsh_inode_map_get - zero is a valid return, and the indicator for errors

### ISSUE THREAD

**Issue by Dr-Emann** [Gottox/libsqsh#121]
> Inode _numbers_ are always non-zero, but inode _references_ aren't, I believe? It appears that `sqsh_inode_map_get(inode_map, 1) == 0`, and so is `sqsh_inode_map_get(inode_map, 9999999) == 0`, but for different reasons

_Originally posted by @Dr-Emann in https://github.com/Gottox/libsqsh/issues/107#issuecomment-1705914702_

**Comment by Gottox** [comment]
Another function to deprecate... ☺️ thank you @Dr-Emann for discovering these issues!

**Comment by Dr-Emann** [comment]
You're welcome, but also sorry ☺️

FYI, I'm working on making rust bindings for `libsqsh`.

**Comment by Gottox** [comment]
I started too, but it's currently non-functional: github.com/Gottox/sqsh-rs

**Comment by Dr-Emann** [comment]
My bindings are still WIP, but are here: https://github.com/Dr-Emann/sqsh-rs/tree/main.
