### ISSUE TITLE
Need more docs on sqsh_file_iterator_skip

### ISSUE THREAD

**Issue by Dr-Emann** [Gottox/libsqsh#134]
**Is your feature request related to a problem? Please describe.**

The docs aren't clear enough for me to understand the expected use of `sqsh_file_iterator_skip`.

1. What is the offset relative to? The beginning of the current `data`, the end of the current `data`, the beginning of the archive?
2. The offset parameter is documented as `@param[in] offset`, but it is taken as `sqsh_index_t *offset`, and does appear to be written to. Need to document what will be in `*offset` after calling the function.
3. Is `sqsh_index_t` (`size_t`) the right type? It seems like an offset into a file could be much larger than a `size_t` on a 32 bit system.

**Describe the solution you'd like**

Docs on the above questions.

**Comment by Gottox** [comment]
Does this answer q1 and q2?

```patch
diff --git a/include/sqsh_file.h b/include/sqsh_file.h
index 6026a4c0..73432283 100644
--- a/include/sqsh_file.h
+++ b/include/sqsh_file.h
@@ -150,11 +150,30 @@ SQSH_NO_UNUSED bool sqsh_file_iterator_next(
  * Note that calling this function will invalidate the data pointer returned by
  * sqsh_file_iterator_data().
  *
- * @param[in,out] iterator The file iterator to skip data in.
- * @param[in] offset        The offset that is contained in the block to skip
- * to.
- * @param[in] desired_size  The desired size of the data to read. May be more or
- * less than the actual size of the data read.
+ * The offset is relative to the beginning of the current block or, if the
+ * iterator hasn't been forwarded with previous calls to
+ * sqsh_file_iterator_skip() or sqsh_file_iterator_next() the beginning of the
+ * first block.
+ *
+ * After calling this function offset is updated to the same position relative
+ * to the new block. See this visualisation:
+ *
+ * ```
+ * |<--- block 8000 --->|
+ *             offset 10000 --^
+ * _skip(i, offset, 1)
+ *                      |<--- block 8000 --->|
+ *              offset 2000 --^
+  ```
+ *
+ * If libsqsh can map more than one block at once, it will do so until
+ * `desired_size` is reached. Note that `desired_size` is only a hint and
+ * libsqsh may return more or less data than requested.
+ *
+ * @param[in,out] iterator      The file iterator to skip data in.
+ * @param[in,out] offset        The offset that is contained in the block to
+ * skip to.
+ * @param[in] desired_size      The desired size of the data to read.
  *
  * @return 0 on success, less than 0 on error.
  */

```

---

For q3:
Yes, it would make sense to have a different datatype (uint64_t for example) for files bigger than 4 GB. Huge files is still an area where libsqsh has rough edges.

**Comment by Dr-Emann** [comment]
I think maybe I have some confusion about what the "current" block means. Does this mean if I do:

```c
SqshFileIterator *it = ...;
sqsh_file_iterator_next(it, 1024);
char *previous_data = memdup(sqsh_file_iterator_data(it), ...);
sqsh_file_iterator_skip(it, 0, 1024);
const char *after_data = sqsh_file_iterator_data(it);
```

Does that mean previous_data will contain the same thing as after_data? I would have expected `offset` to be relative to the end of the current data.

**Comment by Gottox** [comment]
Yes, this should be a nop. The current block is what `_data()` returns.

**Comment by Dr-Emann** [comment]
Interesting, that's not what I would have expected, but that does seem to match what I'm seeing. That doc looks good to me, then.

**Comment by Gottox** [comment]
There are historic reasons why it feels wrong.

There were ideas that `_skip()` required `_next()` to be called afterwards to return valid pointers again. But it felt clumsy and was a potential security flaw. That's why I changed the semantics. The plan was that to the user it should feel like "calling `_next()` `n` times, internally it could do some optimizations. So, back then skip didn't take an offset in bytes but an offset in *blocks*.

It started to break when optimizations where introduced that caused the blocksize to be variable. So `_skip(5)` could yield different results then calling `next()` 5 times when files contain sparse blocks for example. That's why I changed it to byte offsets to work in those scenarios consistently while keeping the noop characteristic of `_skip(0)`.

I guess the combinations of those two semantical changes is why this function feels awkward.

I'm not sure if it makes sense to change the semantics again. But maybe there's a better name than `_skip`?

**Comment by Dr-Emann** [comment]
I honestly think it makes sense if I shift from my "rust iterators" mindset to "c++ iterators" mindset, I'm used to thinking of "the yielded item is now gone, we're on the next one now", so I expected _skip(0) to end getting the next block.

**Comment by Gottox** [comment]
You're right! That's actually a pretty good comparision: Rust iterators hand over ownership, but libsqsh iterators just give you the reference and keep ownership. Actually, that's a design issue with my rust wrapper and Implementing `Iterator<T>` for the libsqsh iterators. I'm pretty sure I can solve it with RefCells somehow, but I haven't worked it out yet.

**Comment by Dr-Emann** [comment]
I think it's actually [fundamentally incompatible](https://github.com/Gottox/sqsh-rs/commit/04938127fa73601ee360fd580a40b2b1e7700191#r127207655) with the Iterator trait, you would want some kind of [streaming or lending iterator](http://lukaskalbertodt.github.io/2018/08/03/solving-the-generalized-streaming-iterator-problem-without-gats.html).

Instead, in my bindings, I've [avoided](https://github.com/Dr-Emann/sqsh-rs/blob/0ee389af606f04d30776bd4756a7ccd2ed201fd3/sqsh-rs/src/directory.rs#L30) the iterator trait, it's only a little less ergonomic to use:
https://github.com/Dr-Emann/sqsh-rs/blob/0ee389af606f04d30776bd4756a7ccd2ed201fd3/sqsh-rs/examples/list_dir_ll.rs#L12-L15. The lifetimes are a little messy, but I believe it's all needed for accuracy: A directory iterator yields names bound to the lifetime of the iterator itself, but allows opening a file which is bound to the lifetime of the original archive, and is totally unbound to the directory iterator.
