### ISSUE TITLE
sqsh_tree_walker_next2 was removed

### ISSUE THREAD

**Issue by Dr-Emann** [Gottox/libsqsh#149]
**Describe the bug**

Other sqsh_tree_walker functions were kept (but deprecated for their path resolver equivalents). Maybe this was intentional, I'm not sure if `sqsh_tree_walker_next2` was considered "released" or not.

As an additional note, the deprecation messages for several `sqsh_tree_walker` functions refer to themselves as the function they were deprecated for (e.g. `sqsh_tree_walker_type` says: `Since 1.2.0. Use sqsh_tree_walker_type() instead`

**Comment by Gottox** [comment]
`sqsh_tree_walker_next2` was never part of any release. The 1.1.x tree does not contain it, the 1.2.x tree is not yet released. So it's now part of the SqshPathResolver class as `sqsh_path_resolver_next`. `SqshTreeWalker` remains as thin shim around `SqshPathResolver` which provides backwards compatibility.

**Comment by Gottox** [comment]
> As an additional note, the deprecation messages for several sqsh_tree_walker functions refer to themselves as the function they were deprecated for (e.g. sqsh_tree_walker_type says: Since 1.2.0. Use sqsh_tree_walker_type() instead

right. That's a c&p mistake.

**Comment by Dr-Emann** [comment]
Awesome, makes sense, thanks.
