### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by probonopd** [Gottox/libsqsh#33]
**Is your feature request related to a problem? Please describe.**

I'd like to consume libsqsh in a Qt based application to extract files from squashfs to files and/or memory.
For this reason, I'd like to have it wrapped in a C++ class.

**Describe the solution you'd like**

Something along those lines with a working `.cpp` implementation

```
#ifndef SQSH_FSEXTRACTOR_H
#define SQSH_FSEXTRACTOR_H

#include <QString>
#include <QByteArray>
#include <QList>
#include <QDir>

#include "SqshFSInfo.h" // Include the previously defined SqshFSInfo class

class SqshFSExtractor
{
public:
    SqshFSExtractor(const QString &imagePath);
    ~SqshFSExtractor();

    SqshFSInfo getFileInfo(const QString &filePath) const;
    QList<SqshFSInfo> listFilesRecursively() const; // Recursive listing; like find /
    QList<SqshFSInfo> listFiles() const; // Directory listing, like ls /

    bool extractToFile(const QString &filePath, const QString &outputFilePath);
    bool extractRecursively(const QString &sourceDir, const QString &targetDir);
    QByteArray extractToMemory(const QString &filePath);

private:
    // Add any private members or helper functions here as needed
};

#endif // SQSH_FSEXTRACTOR_H

```

```
#ifndef SQSH_FSINFO_H
#define SQSH_FSINFO_H

#include <QString>
#include <QVector>

enum class FileType {
    File,
    Directory,
    Symlink,
    Device,
    Other
};

class SqshFSInfo
{
public:
    SqshFSInfo(const QString &name, FileType type, qint64 size = 0);
    ~SqshFSInfo();

    QVector<SqshFSInfo> getChildren() const;
    QString getName() const;
    FileType getType() const;
    qint64 getSize() const;

private:
    QString name;
    FileType type;
    qint64 size;
    QVector<SqshFSInfo> children;
};

#endif // SQSH_FSINFO_H
```

**Additional context**

Unfortunately, I am not able to do this with the current documentation.
Do you think it can be done?
Would you be able to present a sample implementation?

**Comment by probonopd** [comment]
Thanks for your quick response. You are right about `extractRecursively`, it should be done differently.

To get things started, could you point me at working C examples for how to:
* Extract one (small-ish, think icon) known file to memory (following symlinks if needed)
* List all files in the root directory
* 
That would be a tremendous help to get me started. Thank you!

**Comment by Gottox** [comment]
Thanks for the input. That's a great way to improve the documentation!

> * Extract one (small-ish, think icon) known file to memory (following symlinks if needed)

`sqsh_file_content(archive, path)` will do exactly that. It is one of the lesser tested areas in libsqsh, so if you find issues, I'm eager to fix them!

> * List all files in one defined directory (e.g., the root directory)

I just wrote an example for this use case. Have a look in `examples` in the `main` branch.

**Comment by probonopd** [comment]
Thanks @Gottox. Very useful indeed!

I am having issues building it. Using this

```
cmake_minimum_required(VERSION 3.0)
project(libsqsh-examples)

# Set the C++ standard to C++11 or higher
set(CMAKE_CXX_STANDARD 11)

# Find libsqsh using pkg-config
find_package(PkgConfig REQUIRED)
pkg_check_modules(LIBSQSH REQUIRED libsqsh)

# Add the include directories for libsqsh
include_directories(${LIBSQSH_INCLUDE_DIRS})

# Build the 'list_files' executable
add_executable(list_files list_files.c)
target_link_libraries(list_files ${LIBSQSH_LIBRARIES})

# Build the 'list_files_ll' executable
add_executable(list_files_ll list_files_ll.c)
target_link_libraries(list_files_ll ${LIBSQSH_LIBRARIES})
```

I can get it configured, but then the build fails with


```
% make                  
[ 25%] Building C object CMakeFiles/list_files.dir/list_files.c.o
/tmp/libsqsh/examples/list_files.c:20:59: error: too many arguments to function call, expected single argument 'path', have 2 arguments
        struct SqshArchive *archive = sqsh_archive_open(argv[1], NULL);
                                      ~~~~~~~~~~~~~~~~~          ^~~~
/usr/include/sys/_null.h:34:14: note: expanded from macro 'NULL'                                 
#define NULL    ((void *)0)
                ^~~~~~~~~~~
/usr/local/include/sqsh/sqsh_chrome.h:62:21: note: 'sqsh_archive_open' declared here             
struct SqshArchive *sqsh_archive_open(const char *path);
                    ^
1 error generated.                                                                               
*** Error code 1


```

**Comment by Gottox** [comment]
A few bits and pieces of the API are currently unstable, so if you run into problems, either wait for the 0.6.0 release or use the main branch for now.

**Comment by probonopd** [comment]
Realized that I had an install from yesterday night; reinstalled the library and the example compiles.

**Comment by probonopd** [comment]
I can confirm that the example works for me.

```
% mksquashfs squashfs-root test.sfs -comp zstd

% /tmp/libsqsh/examples/build/list_files test.sfs 
.DirIcon
AppRun
appimagetool.desktop
appimagetool.png
usr

% /tmp/libsqsh/examples/build/list_files_ll test.sfs 
.DirIcon
AppRun
appimagetool.desktop
appimagetool.png
usr
```

**Comment by probonopd** [comment]
The only thing that does not work yet is extracting the data if the file is actually a symlink. Can you point me to a solution for this?
Thanks again for your help, which is tremendous.

**Comment by Gottox** [comment]
I think that's an actual bug. At least that's a blind spot in the unit tests.

**Comment by probonopd** [comment]
Should I open a new issue for it?

**Comment by Gottox** [comment]
Yes please! - I created a unit test for following symlinks, but I cannot reproduce the issue at the moment.

**Comment by Gottox** [comment]
At least the high level API (sqsh_file_contents, sqsh_directory_list) should work transparently on symlinks.
