### ISSUE TITLE
Support squashfs files that start at an offset

### ISSUE THREAD

**Issue by probonopd** [Gottox/libsqsh#34]
**Is your feature request related to a problem? Please describe.**

The [AppImage](https://appimage.org/) file format conists of an ELF to the end of which a squashfs file is appended.

**Describe the solution you'd like**

I would like to use libsqsh on such squashfs files that don't start at offset `0` but at another offset.
Hence, I am looking for

* An example to extract from such files (like [sqsh_file_content(archive, path)](https://github.com/Gottox/libsqsh/blob/a2b8ccd238b9b7dc720ed6686ceaa1f40ff727d9/include/sqsh_chrome.h#L139))
* An example how to list directories from such files (like https://github.com/Gottox/libsqsh/tree/main/examples)

**Additional context**

This library could become really, really useful in the context of the AppImage ecosystem (e.g., file managers that want to show the proper icons for AppImages, etc.); for this the offset functionality is essential. Thanks for making this library, for licensing it under a permissive license, and for your support! :+1: 

Here is an example file: [appimagetool-x86_64.AppImage](https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage) - the squashfs starts at offset `631200`.

References
* https://github.com/plougher/squashfs-tools/blob/e43ebfc3a6fa6bde5a176d077486b3419fec5b36/squashfs-tools/unsquashfs.c#L4143-L4151
* https://github.com/plougher/squashfs-tools/blob/e43ebfc3a6fa6bde5a176d077486b3419fec5b36/squashfs-tools/unsquashfs.c#L53
* https://github.com/vasi/squashfuse/pull/7

**Comment by Gottox** [comment]
I introduced offset handling. Just set `archive_offset` to the desired offset. 

Source based on on `examples/list_files_ll.c`:

```c
#include <sqsh.h>
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char *argv[]) {
	int error_code = 0;
	if (argc != 2) {
		printf("Usage: %s <sqsh-file>\n", argv[0]);
		return 1;
	}
	struct SqshConfig config = {
		// Read the header file to find documentation on these fields.
		// It's safe to set them all to 0.
		.source_mapper = sqsh_mapper_impl_mmap,
		.source_size = 0,
		.mapper_block_size = 0,
		.mapper_lru_size = 0,
		.compression_lru_size = 0,
		.archive_offset = 631200, // <=======================================
	};
	struct SqshArchive *archive =
			sqsh_archive_new(argv[1], &config, &error_code);
	if (error_code != 0) {
		sqsh_perror(error_code, "sqsh_archive_new");
		return 1;
	}
	const struct SqshSuperblock *superblock = sqsh_archive_superblock(archive);
	uint64_t inode_root_ref = sqsh_superblock_inode_root_ref(superblock);
	struct SqshInode *inode =
			sqsh_inode_new(archive, inode_root_ref, &error_code);
	if (error_code != 0) {
		sqsh_perror(error_code, "sqsh_inode_new");
		return 1;
	}

	struct SqshDirectoryIterator *iterator =
			sqsh_directory_iterator_new(inode, &error_code);
	if (error_code != 0) {
		sqsh_perror(error_code, "sqsh_directory_iterator_new");
		return 1;
	}

	while (sqsh_directory_iterator_next(iterator) > 0) {
		const char *name = sqsh_directory_iterator_name(iterator);
		size_t size = sqsh_directory_iterator_name_size(iterator);
		fwrite(name, size, 1, stdout);
		fputc('\n', stdout);
	}

	sqsh_directory_iterator_free(iterator);
	sqsh_inode_free(inode);
	sqsh_archive_close(archive);
}
```
Output:
```bash
# build/examples/list_files_ll appimagetool-x86_64.AppImage
.DirIcon
AppRun
appimagetool.desktop
appimagetool.png
usr
```

**Comment by probonopd** [comment]
Thank you very much. This works for me :+1:
