### ISSUE TITLE
Downgrade build system requirements to allow building on Ubuntu 20.04

### ISSUE THREAD

**Issue by probonopd** [Gottox/libsqsh#35]
**Is your feature request related to a problem? Please describe.**
I frequently build binaries that are supposed to run on all still-supported LTS releases of Ubuntu.
Currently, libsqsh can only be built on 22.04 but not on 20.04, due to it needing a newer meson.

**Describe the solution you'd like**
It would be nice if build system requirements could be downgraded to allow building on Ubuntu 20.04.

**Describe alternatives you've considered**
Get a newer meson (and whatnot) onto Ubuntu 20.04, but it is not a great solution because it adds work for every such distribution (e.g., CentOS)

**Additional context**
I consider building binaries on the oldest still-supported LTS releases of Ubuntu best practice, so that the binaries can run on more target systems and not only on the latest and greatest ones.

**Comment by Gottox** [comment]
I just looked at the source. `meson-0.57` is only needed for `-Ddoc=true` and for `-Dtest=true`. I'm removing the min requirement.

**Comment by probonopd** [comment]
Thank you very much. For testing, could you use `runs-on:  ubuntu-20.04` here?

https://github.com/Gottox/libsqsh/blob/d9b0e49f477b8d8be1bb2e85975a97c578878919/.github/workflows/ci.yaml#L11

**Comment by probonopd** [comment]
Have you tested it? This is what I get...

```
           meson setup build \
            -Dwerror=false \
            -Dexamples=false  \
            -Dcurl=disabled  \
            -Dzlib=enabled \
            -Dlz4=disabled \
            -Dlzma=disabled  \
            -Dzstd=enabled  \
            -Dthreads=enabled \
            -Ddoc=false \
            -Dtest=false
           cd build
           ls
           meson compile
```

Result:

```
Version: 0.53.2
Source dir: /home/runner/work/Filer/Filer/libsqsh
Build dir: /home/runner/work/Filer/Filer/libsqsh/build
Build type: native build
Project name: libsqsh
Project version: 0.5.0
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Run-time dependency threads found: YES
Dependency libcurl skipped: feature curl disabled
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Found CMake: /usr/local/bin/cmake (3.27.0)
Run-time dependency fuse3 found: NO (tried pkgconfig and cmake)
Dependency fuse skipped: feature fuse-old disabled
Dependency liblz4 skipped: feature lz4 disabled
Dependency liblzma skipped: feature lzma disabled
Run-time dependency zlib found: YES 1.2.11
Run-time dependency libzstd found: YES 1.4.4
Configuring sqsh-cat.1 using configuration
Configuring sqsh-ls.1 using configuration
Configuring sqsh-stat.1 using configuration
Configuring sqsh-unpack.1 using configuration
Configuring sqsh-xattr.1 using configuration
Build targets in project: 7

Found ninja-1.10.0 at /usr/bin/ninja
build.ninja
compile_commands.json
include
lib
man
meson-info
meson-logs
meson-private
tools

ERROR: Neither directory contains a build file meson.build.
Error: Process completed with exit code 1.

```

**Comment by Gottox** [comment]
I tried `ninja` instead of `meson compile`, that worked for me.

**Comment by probonopd** [comment]
I can confirm that. Thanks! :+1:
