### ISSUE TITLE
Cannot extract data from squashfs file with offset if data is in a symlinked file

### ISSUE THREAD

**Issue by probonopd** [Gottox/libsqsh#36]
**Describe the bug**
Cannot extract data from squashfs file with offset if data is in a symlinked file

**To Reproduce**

[This file](https://github.com/dragotin/kraft/releases/download/v1.0/Kraft-v1.0-x86_64.AppImage) contains a `.DirIcon` which is a symlink. The squashfs offset is `193728`.

**Expected behavior**
The data of the `.DirIcon` gets extracted,

**Platform (please complete the following information):**
 - Operating System: FreeBSD
 - Version 13.1

**Additional context**
I am using code similar to https://github.com/Gottox/libsqsh/blob/main/examples/read_file_ll.c.

If this is not possible with ll, then either I need to know how to (recursively) resolve symlinks on my own, or it should become possible to use an offset in the high level version.

**Comment by Gottox** [comment]
I actually just fixed a bug in the symlink handling, but your use case is actually not triggering it. `sqsh_open()` should resolve symlinks just fine:

```diff
diff --git a/examples/read_file_ll.c b/examples/read_file_ll.c
index 7275a9d0..3dada32d 100644
--- a/examples/read_file_ll.c
+++ b/examples/read_file_ll.c
@@ -25,7 +25,7 @@ main(int argc, char *argv[]) {
                        .mapper_block_size = 0,
                        .mapper_lru_size = 0,
                        .compression_lru_size = 0,
-                       .archive_offset = 0,
+                       .archive_offset = 193728,
        };
        struct SqshArchive *archive =
                        sqsh_archive_new(argv[1], &config, &error_code);
```

```bash
# build/examples/read_file_ll Kraft-v1.0-x86_64.AppImage /.DirIcon | wc 
   1568    8959  148760
```

I also added the `-o OFFSET` flag to the sqsh-* tools in `main`:

```bash
build/tools/sqsh-cat -o 193728 Kraft-v1.0-x86_64.AppImage /.DirIcon | wc   
   1568    8959  148760
```

Could you post code, that triggers the issue?

Also just in case, could you retry with the current `main`?

**Comment by probonopd** [comment]
It is working fine. Sorry for the noise.

Turns out the issue was neither in your nor in my code; that particular (third-party) AppImage is indeed shipping a HTML file with a `.svg` suffix, symlinked as `.DirIcon`. No wonder this won't work. The data gets extracted fine, but my code has issues making an icon out of it ;-)
